# Project needs python 1.8 [ignored, using 3] and torch 1.7
FROM pytorch/pytorch:1.7.0-cuda11.0-cudnn8-runtime

#############################
### Install dependencies  ###
#############################

RUN apt-get update && \
    apt-get install ffmpeg libsm6 libxext6  -y
RUN conda install -c conda-forge opencv=4.3.0 && \
    conda install -c conda-forge python-spams
COPY ./reqs.txt ./reqs.txt
RUN pip install -r ./reqs.txt

WORKDIR /MACNN
RUN mkdir models
