version: "3"

services:
  macnn_srv:
    image: macnn:latest
    container_name: "macnn_cnt"
    command: bash -c "python MACNN.py --dataset_name DOTA  --dataset_path /MACNN/DS --batch_size 8 --image_size 110"
    volumes:
      - <dataset path>:/MACNN/DS
      - <model save path>:/MACNN/MACNN2_output/
      - ./:/MACNN
      - <output dir>:/MACNN/outputs
    deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
    shm_size: 10gb
